run:
  skip-dirs-use-default: false

linters:
  enable-all: true
  disable:
    - depguard
    - revive
    - forbidigo
    - gochecknoinits
    - paralleltest
    - gochecknoglobals
    - varnamelen
    - forcetypeassert
    - ireturn

    - structcheck
    - interfacer
    - deadcode
    - varcheck
    - ifshort
    - exhaustivestruct
    - golint
    - maligned
    - nosnakecase
    - scopelint

linters-settings:
  gocyclo:
    min-complexity: 15

  cyclop:
    max-complexity: 20

issues:
  exclude-use-default: false
