linters:
  enable-all: true
  disable:
    - gochecknoinits
    - paralleltest
    - wrapcheck
    - gosec
    - gochecknoglobals
    - musttag
    - depguard
    - forcetypeassert
    - varnamelen
    - ireturn
    - err113
    - nlreturn
    - wsl

    # Deprecated ones:
    - execinquery
    - gomnd
    - exportloopref

issues:
  exclude-files:
    - cmd/goe/shell.go
    - pkg/dotenv/parser.go
