run:
  skip-dirs:
    - pkg/envparse

linters:
  enable-all: true
  disable:
    - depguard
    - revive
    - forbidigo
    - gochecknoinits
    - paralleltest
    - gochecknoglobals
    - varnamelen
    - forcetypeassert
    - ireturn
    - prealloc
    - stylecheck
    - tagalign
    - govet

    - structcheck
    - interfacer
    - deadcode
    - varcheck
    - ifshort
    - exhaustivestruct
    - golint
    - maligned
    - nosnakecase
    - scopelint
