run:
  skip-dirs-use-default: false

linters:
  enable-all: true
  disable:
    - depguard
    - revive
    - forbidigo
    - gochecknoinits
    - paralleltest
    - gochecknoglobals
    - varnamelen

    - structcheck
    - interfacer
    - deadcode
    - varcheck
    - ifshort
    - exhaustivestruct
    - golint
    - maligned
    - nosnakecase
    - scopelint

gocyclo:
  min-complexity: 15

issues:
  exclude-use-default: false
