name: Go
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: actions/checkout@v3

      - name: lint
        run: go run github.com/ysmood/golangci-lint@latest
        if: matrix.os == 'ubuntu-latest'

      - name: test
        run: go test -coverprofile="coverage.out" ./...

      - name: check coverage
        run: go run github.com/ysmood/got/cmd/check-cov@latest -min 80
